import random
from typing import List

def _sample(items: List[str], k_min: int = 0, k_max: int = None) -> List[str]:
    """Sample between k_min and k_max items from the list."""
    if not items:
        return []
    if k_max is None:
        k_max = len(items)
    k_min = max(0, min(k_min, len(items)))
    k_max = max(k_min, min(k_max, len(items)))
    k = random.randint(k_min, k_max)
    return random.sample(items, k)

# STRICT ROBOT PROFILES FOR ROBOT GENERATION
STRICT_ROBOT_PROFILES = [
    {
        "name": "misty_communication",
        "mobility_type": "wheeled",
        "environmental_resistance": [],
        "sensors": ["camera", "microphone"],
        "manipulators": [],
        "communication_protocols": ["Wi-Fi"],
        "special_functions": ["speech output", "facial recognition", "gesture recognition", "status reporting"],
        "safety_features": ["obstacle detection", "emergency stop"],
        "sensor_range": 5.0,
        "processing_power": 4.0,
        "autonomy_level": "semi-autonomous",
        "payload_capacity": 0.0,
        "reach": 0.0,
        "battery_life": 60.0,
        "size": (0.5, 0.5, 1.0),
        "adaptability": True
    },
       {
        "name": "husky_heavy_transport",
        "mobility_type": "wheeled",
        "environmental_resistance": ["weatherproof", "dustproof", "shock-resistant"],
        "sensors": ["LiDAR", "camera", "GPS", "proximity sensor"],
        "manipulators": [],
        "communication_protocols": ["Wi-Fi", "Radio"],
        "special_functions": ["object recognition", "object tracking", "path planning"],
        "safety_features": ["obstacle detection", "collision avoidance", "emergency stop", "overload protection"],
        "sensor_range": 20.0,
        "processing_power": 6.5,
        "autonomy_level": "semi-autonomous",
        "payload_capacity": 25.0,
        "reach": 0.0,
        "battery_life": 90.0,
        "size": (1.0, 0.7, 0.5),
        "adaptability": True
    },
    {
        "name": "pioneer3at_medium_delivery",
        "mobility_type": "wheeled",
        "environmental_resistance": ["dustproof", "shock-resistant"],
        "sensors": ["camera", "proximity sensor", "ultrasonic"],
        "manipulators": [],
        "communication_protocols": ["Wi-Fi"],
        "special_functions": ["object recognition", "object tracking", "path planning"],
        "safety_features": ["obstacle detection", "collision avoidance", "emergency stop"],
        "sensor_range": 12.0,
        "processing_power": 5.0,
        "autonomy_level": "semi-autonomous",
        "payload_capacity": 8.0,
        "reach": 0.0,
        "battery_life": 75.0,
        "size": (0.7, 0.6, 0.4),
        "adaptability": True
    },
    {
        "name": "turtlebot3_waffle_scout",
        "mobility_type": "wheeled",
        "environmental_resistance": [],
        "sensors": ["LiDAR", "camera", "proximity sensor"],
        "manipulators": [],
        "communication_protocols": ["Wi-Fi"],
        "special_functions": ["object recognition", "object tracking", "path planning"],
        "safety_features": ["obstacle detection", "collision avoidance", "emergency stop"],
        "sensor_range": 10.0,
        "processing_power": 4.5,
        "autonomy_level": "fully autonomous",
        "payload_capacity": 1.0,
        "reach": 0.0,
        "battery_life": 65.0,
        "size": (0.4, 0.4, 0.3),
        "adaptability": True
    },
    {
        "name": "delivery",
        "mobility_type": "aerial",
        "environmental_resistance": ["weatherproof", "heat-resistant", "cold-resistant"],
        "sensors": ["LiDAR", "GPS", "proximity sensor", "camera"],
        "manipulators": ["gripper"],
        "communication_protocols": ["Wi-Fi", "4G"],
        "special_functions": ["object recognition", "object tracking", "facial recognition"],
        "safety_features": ["obstacle detection", "emergency stop"],
        "sensor_range": 25.0,
        "processing_power": 5.0,
        "autonomy_level": "fully autonomous",
        "payload_capacity": 20.0,
        "reach": 0.0,
        "battery_life": 80.0,
        "size": (2.0, 2.0, 2.0),
        "adaptability": False
    },
    {
        "name": "assembly",
        "mobility_type": "hovering",
        "environmental_resistance": ["dustproof", "heat-resistant", "shock-resistant"],
        "sensors": ["camera", "proximity sensor", "infrared"],
        "manipulators": ["gripper", "drill", "dispenser", "welding tool"],
        "communication_protocols": ["Wi-Fi", "Radio"],
        "special_functions": ["object recognition", "object tracking", "gesture recognition", "precise alignment"],
        "safety_features": ["collision avoidance", "overheat protection", "emergency stop"],
        "sensor_range": 10.0,
        "processing_power": 7.0,
        "autonomy_level": "semi-autonomous",
        "payload_capacity": 20.0,
        "reach": 5.0,
        "battery_life": 75.0,
        "size": (3.0, 2.0, 2.0),
        "adaptability": True
    },
    {
        "name": "excavator",
        "mobility_type": "tracked",
        "environmental_resistance": ["dustproof", "shock-resistant", "weatherproof"],
        "sensors": ["LiDAR", "camera", "proximity sensor", "magnetometer"],
        "manipulators": ["hydraulic bucket", "cable hoist"],
        "communication_protocols": ["Wi-Fi", "Radio"],
        "special_functions": ["terrain leveling", "object recognition"],
        "safety_features": ["collision avoidance", "overload protection", "emergency stop"],
        "sensor_range": 15.0,
        "processing_power": 8.0,
        "autonomy_level": "semi-autonomous",
        "payload_capacity": 20.0,
        "reach": 8.0,
        "battery_life": 75.0,
        "size": (4.2, 2.5, 3.0),
        "adaptability": True
    },
    {
        "name": "bricklayer",
        "mobility_type": "wheeled",
        "environmental_resistance": ["dustproof", "waterproof", "shock-resistant"],
        "sensors": ["infrared", "camera", "proximity sensor"],
        "manipulators": ["mixer drum", "dispenser", "gripper", "cable hoist"],
        "communication_protocols": ["Wi-Fi", "Radio"],
        "special_functions": ["precise alignment", "concrete mixing"],
        "safety_features": ["obstacle detection", "emergency stop", "collision avoidance"],
        "sensor_range": 10.0,
        "processing_power": 5.5,
        "autonomy_level": "semi-autonomous",
        "payload_capacity": 20.0,  
        "reach": 5.5,
        "battery_life": 80.0,
        "size": (4.0, 2.0, 2.0),
        "adaptability": False
    },
    {
        "name": "crane",
        "mobility_type": "tracked", 
        "environmental_resistance": ["weatherproof", "wind-resistant", "dustproof"],
        "sensors": ["camera", "GPS", "proximity sensor", "ultrasonic"],
        "manipulators": ["gripper", "cable hoist"],
        "communication_protocols": ["5G", "Radio"],
        "special_functions": ["precise alignment", "object tracking", "object detection"],
        "safety_features": ["overload protection", "balance control", "collision avoidance", "emergency stop"],
        "sensor_range": 30.0,
        "processing_power": 6.5,
        "autonomy_level": "semi-autonomous",
        "payload_capacity": 35.0,
        "reach": 30.0,
        "battery_life": 70.0,
        "size": (3.5, 3.5, 10.0),
        "adaptability": False
    },
    {
        "name": "scaffolding",
        "mobility_type": "climbing",
        "environmental_resistance": ["dustproof", "shock-resistant", "wind-resistant"],
        "sensors": ["LiDAR", "camera", "ultrasonic", "proximity sensor"],
        "manipulators": ["gripper", "drill", "welding tool", "cable hoist"],
        "communication_protocols": ["Wi-Fi", "Bluetooth"],
        "special_functions": ["precise alignment", "balance control"],
        "safety_features": ["fall detection", "collision avoidance", "emergency stop"],
        "sensor_range": 12.0,
        "processing_power": 7.0,
        "autonomy_level": "fully autonomous",
        "payload_capacity": 20.0,  
        "reach": 10.0,  
        "battery_life": 65.0,
        "size": (1.5, 1.0, 2.0),
        "adaptability": True
    }
]

# STRICT TASK PROFILES FOR TASK GENERATION
STRICT_TASK_PROFILES = [
    {
    	"task_type": "assistance",
    	"priority_level": "medium",
    	"reward": 5,
    	"difficulty": 2,
    	"navigation_constraints": [],
    	"required_capabilities": [],
    	"environmental_conditions": [],
    	"tools_needed": [["camera", "microphone"], []],
        "communication_requirements": ["Wi-Fi"],
        "safety_protocols": ["obstacle detection", "emergency stop"],
        "duration": 3,
        "performance_metric": "completion rate",
        "nl_description": "Navigate to a checkpoint and verbally report status or instructions to a human/operator."
    },
    {
        "task_type": "utilities", #gripper
        "priority_level": random.choice(["medium", "high"]),
        "reward": random.randint(5, 8),
        "difficulty": random.randint(5, 8),
        "navigation_constraints": _sample(["uneven floors", "loose debris", "slippery"], 0, 3),
        "required_capabilities": _sample(["payload >= 10", "reach >= 3"], 0, 2),
        "environmental_conditions": _sample(["weatherproof", "dustproof", "shock-resistance"], 0, 3),
        "tools_needed": [["LiDAR", "camera", "proximity sensor"], ["gripper"]],
        "communication_requirements": ["Radio", "Wi-Fi"],
        "safety_protocols": ["overload protection", "balance control", "emergency stop"],
        "duration": random.randint(3, 6),
        "performance_metric": "safety compliance",
        "nl_description": "Operate valves, switches, and panels; carry small parts; precise manipulation in plant rooms."
    },
    {
        "task_type": "utilities", #bucket
        "priority_level": random.choice(["medium", "high"]),
        "reward": random.randint(5, 8),
        "difficulty": random.randint(5, 8),
        "navigation_constraints": _sample(["uneven floors", "loose debris", "slippery"], 0, 3),
        "required_capabilities": _sample(["payload >= 10", "reach >= 3"], 0, 2),
        "environmental_conditions": _sample(["weatherproof", "dustproof", "shock-resistance"], 0, 3),
        "tools_needed": [["LiDAR", "camera", "proximity sensor"], ["hydraulic bucket"]],
        "communication_requirements": ["Radio", "Wi-Fi"],
        "safety_protocols": ["overload protection", "balance control", "emergency stop"],
        "duration": random.randint(3, 6),
        "performance_metric": "safety compliance",
        "nl_description": "Transport construction materials, clear or move small bulk materials near utility corridors; load/unload with a bucket."
    },
    {
        "task_type": "debris", #gripper
        "priority_level": random.choice(["medium", "high"]),
        "reward": random.randint(4, 7),
        "difficulty": random.randint(4, 7),
        "navigation_constraints": _sample(["loose debris", "uneven floors", "crowded"], 0, 2),
        "required_capabilities": [f"payload >= {random.randint(10,15)}", f"reach >= {random.randint(0,3)}"],
        "environmental_conditions": _sample(["weatherproof", "wind-resistant"], 0, 2),
        "tools_needed": [["LiDAR", "camera", "ultrasonic", "proximity sensor"], _sample(["gripper"], 1, 1)],
        "communication_requirements": ["Radio", "Wi-Fi"],
        "safety_protocols": ["overload protection", "balance control", "emergency stop"],
        "duration": random.randint(3, 6),
        "performance_metric": "safety compliance",
        "nl_description": "Pick and remove scattered debris in cluttered passages; careful grasping and placement."
    },
    {
        "task_type": "debris", #bucket
        "priority_level": random.choice(["medium", "high"]),
        "reward": random.randint(4, 7),
        "difficulty": random.randint(4, 7),
        "navigation_constraints": _sample(["loose debris", "uneven floors", "crowded"], 0, 2),
        "required_capabilities": [f"payload >= {random.randint(10,15)}", f"reach >= {random.randint(0,3)}"],
        "environmental_conditions": _sample(["weatherproof", "wind-resistant"], 0, 2),
        "tools_needed": [["LiDAR", "camera", "ultrasonic", "proximity sensor"], ["hydraulic bucket"]],
        "communication_requirements": ["Radio", "Wi-Fi"],
        "safety_protocols": ["overload protection", "balance control", "emergency stop"],
        "duration": random.randint(3, 6),
        "performance_metric": "safety compliance",
        "nl_description": "Scoop and relocate piles of loose debris; continuous removal in uneven terrain.",
        
    },
    {
        "task_type": "delivery",
        "priority_level": random.choice(["low", "medium"]),
        "reward": random.randint(2, 5),
        "difficulty": random.randint(2, 5),
        "navigation_constraints": _sample(["uneven floors", "crowded", "slippery", "elevator", "stairs"], 0),
        "required_capabilities": _sample(["payload >= 1.0", "payload >= 5.0", "payload >= 10.0"], 1, 1),
        "environmental_conditions": _sample(["weatherproof", "dustproof"], 1, 1),
        "tools_needed": [["camera", "proximity sensor", "GPS"], ["gripper"]],
        "communication_requirements": ["Wi-Fi", "4G"],
        "safety_protocols": ["obstacle detection", "emergency stop"],
        "duration": random.randint(2, 5),
        "performance_metric": "time taken",
        "nl_description": "Fetch-and-carry small payloads point-to-point through indoor/outdoor corridors.",
    },
    {
        "task_type": "assembly",
        "priority_level": random.choice(["medium", "high"]),
        "reward": random.randint(5, 7),
        "difficulty": random.randint(5, 7),
        "navigation_constraints": _sample(["crowded", "loose debris", "slippery", "low ceilings"], 0, 2),
        "required_capabilities": _sample(["reach >= 1.5", "reach >= 3.0", "reach >= 5.0", "payload >= 10.0"], 1, 1),
        "environmental_conditions": _sample(["dustproof", "shock-resistant", "heat-resistant"], 0, 3),
        "tools_needed": [["camera", "infrared", "dispenser"], ["gripper", "drill", "welding tool"]],
        "communication_requirements": ["Wi-Fi", "Radio"],
        "safety_protocols": ["collision avoidance", "emergency stop"],
        "duration": random.randint(4, 7),
        "performance_metric": "accuracy",
        "nl_description": "Fixture placement, fastening, dispensing, or welding with moderate precision in crowded areas.",
    },
    {
        "task_type": "excavate",
        "priority_level": random.choice(["high", "urgent"]),
        "reward": random.randint(6, 9),
        "difficulty": random.randint(6, 8),
        "navigation_constraints": _sample(["uneven floors", "loose debris", "low visibility"], 0, 3),
        "required_capabilities": [f"payload >= {random.randint(15, 20)}", f"reach >= {random.randint(2,7)}"],
        "environmental_conditions": _sample(["dustproof", "shock-resistant", "weatherproof"], 0, 3),
        "tools_needed": [["LiDAR", "camera", "proximity sensor"], ["hydraulic bucket"]],
        "communication_requirements": ["Radio"],
        "safety_protocols": ["overload protection", "obstacle detection"],
        "duration": random.randint(5, 7),
        "performance_metric": "safety compliance",
        "nl_description": "Dig, trench, or remove soil/rubble; sustained scooping with high payload demands.",
    },
    {
        "task_type": "item elevation",
        "priority_level": random.choice(["low", "medium"]),
        "reward": random.randint(4, 8),
        "difficulty": random.randint(4, 8),
        "navigation_constraints": _sample(["low visibility", "crowded", "uneven floors"], 0, 3),
        "required_capabilities": [f"reach >= {random.randint(15, 25)}", "payload >= 15"],
        "environmental_conditions": _sample(["weatherproof", "wind-resistant"], 0, 2),
        "tools_needed": [["camera", "GPS", "proximity sensor", "ultrasonic"], ["cable hoist", "gripper"]],
        "communication_requirements": ["Radio", "Wi-Fi"],
        "safety_protocols": ["overload protection", "emergency stop"],
        "duration": random.randint(3, 5),
        "performance_metric": "safety compliance",
        "nl_description": "Lift and hold items at height; stable hoisting and precise placement are important.",
    },
    {
        "task_type": "lay bricks",
        "priority_level": "medium",
        "reward": random.randint(6, 12),
        "difficulty": random.randint(6, 12),
        "navigation_constraints": _sample(["crowded", "low visibility", "windy"], 0, 3),
        "required_capabilities": [f"reach >= {random.randint(2,4)}", f"payload >= {random.randint(8,10)}"],
        "environmental_conditions": _sample(["dustproof", "weatherproof"], 0, 2),
        "tools_needed": [["LiDAR", "camera", "proximity sensor"], ["gripper", "dispenser"]],
        "communication_requirements": ["Wi-Fi"],
        "safety_protocols": ["collision avoidance", "overheat protection"],
        "duration": random.randint(6, 10),
        "performance_metric": "accuracy",
        "nl_description": "Pick, mortar/dispense, and place bricks with consistent accuracy and alignment.",
    },
    {
        "task_type": "scaffold",
        "priority_level": "medium",
        "reward": random.randint(5, 8),
        "difficulty": random.randint(5, 8),
        "navigation_constraints": _sample(["narrow spaces", "low ceilings", "windy"], 0, 3),
        "required_capabilities": [f"payload >= {random.randint(8, 10)}", f"reach >= {random.randint(2, 3)}"],
        "environmental_conditions": _sample(["weatherproof", "wind-resistant"], 0, 2),
        "tools_needed": [["LiDAR", "camera", "ultrasonic", "proximity sensor"], ["gripper", "drill"]],
        "communication_requirements": ["Radio", "Wi-Fi"],
        "safety_protocols": ["overload protection", "balance control", "emergency stop"],
        "duration": random.randint(3, 6),
        "performance_metric": "safety compliance",
        "nl_description": "Work at elevation around narrow or vertical structures; drilling and placement on frames.",
    }
]
